[pytest]
addopts = -v --maxfail=10 --html=Reports/HTML_Report.html
markers = 
    great: used for tests that use the greater than operator
    less: used for tests that use the lesser than operator
    activities: used to mark tests as activities